<?xml version="1.0" encoding="utf-8"?><Database Name="FiglutSpread" Class="FiglutSpreadDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PAULKOLOZSV38D1\MSSQLSERVER2012;Initial Catalog=FiglutSpread;Persist Security Info=True;User ID=sa" SettingsObjectName="Figlut.Spread.ORM.Properties.Settings" SettingsPropertyName="FiglutSpreadConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EmailLog" Member="EmailLogs">
    <Type Name="EmailLog">
      <Column Name="EmailLogId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ErrorCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ErrorMessage" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="MessageContents" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TableReference" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RecordReference" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Tag" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EmailProviderCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WebRequestActivity" Member="WebRequestActivities">
    <Type Name="WebRequestActivity">
      <Column Name="WebRequestActivityId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RequestVerb" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RequestUrl" Type="System.String" DbType="VarChar(2048)" CanBeNull="true" />
      <Column Name="RequestReferrerUrl" Type="System.String" DbType="VarChar(2048)" CanBeNull="true" />
      <Column Name="Controller" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UserAgent" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UserHostAddress" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="UserHostName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClientType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsCrawler" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsMobileDevice" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MobileDeviceManufacturer" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="MobileDeviceModel" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Platform" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="SourceApplication" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="WhoIsStatus" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="WhoIsCountry" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="WhoIsCountryCode" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="WhoIsRegion" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="WhoIsRegionName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="WhoIsCity" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="WhoIsZip" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="WhoIsLatitude" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="WhoIsLongitude" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="WhoIsTimeZone" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="WhoIsISP" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="WhoIsOrg" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_WebRequestActivity" Member="User" AccessModifier="Internal" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.GlobalSetting" Member="GlobalSettings">
    <Type Name="GlobalSetting">
      <Column Name="GlobalSettingId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SettingName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SettingValue" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="LastDateUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="InvoiceId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InvoiceNumber" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreatedByUserName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="OrganizationId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Invoice_InvoiceItem" Member="InvoiceItems" ThisKey="InvoiceId" OtherKey="InvoiceId" Type="InvoiceItem" />
      <Association Name="Organization_Invoice" Member="Organization" AccessModifier="Internal" ThisKey="OrganizationId" OtherKey="OrganizationId" Type="Organization" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="User_Invoice" Member="User" AccessModifier="Internal" ThisKey="CreatedByUserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceItem" Member="InvoiceItems">
    <Type Name="InvoiceItem">
      <Column Name="InvoiceItemId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InvoiceId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LineNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalItemPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Invoice_InvoiceItem" Member="Invoice" AccessModifier="Internal" ThisKey="InvoiceId" OtherKey="InvoiceId" Type="Invoice" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderNumber" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreatedByUserName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="OrganizationId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Order_OrderItem" Member="OrderItems" ThisKey="OrderId" OtherKey="OrderId" Type="OrderItem" />
      <Association Name="Organization_Order" Member="Organization" AccessModifier="Internal" ThisKey="OrganizationId" OtherKey="OrganizationId" Type="Organization" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="User_Order" Member="User" AccessModifier="Internal" ThisKey="CreatedByUserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderItem" Member="OrderItems">
    <Type Name="OrderItem">
      <Column Name="OrderItemId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="OrderId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LineNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalItemPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Order_OrderItem" Member="Order" AccessModifier="Internal" ThisKey="OrderId" OtherKey="OrderId" Type="Order" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Organization" Member="Organizations">
    <Type Name="Organization">
      <Column Name="OrganizationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Identifier" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SmsCreditsBalance" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="AllowSmsCreditsDebt" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OrganizationSubscriptionTypeId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OrganizationSubscriptionEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BillingDayOfTheMonth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Organization_Invoice" Member="Invoices" ThisKey="OrganizationId" OtherKey="OrganizationId" Type="Invoice" />
      <Association Name="Organization_Order" Member="Orders" ThisKey="OrganizationId" OtherKey="OrganizationId" Type="Order" />
      <Association Name="Organization_SmsMessageTemplate" Member="SmsMessageTemplates" ThisKey="OrganizationId" OtherKey="OrganizationId" Type="SmsMessageTemplate" />
      <Association Name="Organization_SmsReceivedLog" Member="SmsReceivedLogs" ThisKey="OrganizationId" OtherKey="OrganizationId" Type="SmsReceivedLog" />
      <Association Name="Organization_SmsSentLog" Member="SmsSentLogs" ThisKey="OrganizationId" OtherKey="OrganizationId" Type="SmsSentLog" />
      <Association Name="Organization_User" Member="Users" ThisKey="OrganizationId" OtherKey="OrganizationId" Type="User" />
      <Association Name="Organization_Subscription" Member="Subscriptions" ThisKey="OrganizationId" OtherKey="OrganizationId" Type="Subscription" />
      <Association Name="OrganizationSubscriptionType_Organization" Member="OrganizationSubscriptionType" AccessModifier="Internal" ThisKey="OrganizationSubscriptionTypeId" OtherKey="OrganizationSubscriptionTypeId" Type="OrganizationSubscriptionType" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.OrganizationSubscriptionType" Member="OrganizationSubscriptionTypes">
    <Type Name="OrganizationSubscriptionType">
      <Column Name="OrganizationSubscriptionTypeId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MonthlySubscriptionPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="SmsUnitPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="OrganizationSubscriptionType_Organization" Member="Organizations" ThisKey="OrganizationSubscriptionTypeId" OtherKey="OrganizationSubscriptionTypeId" Type="Organization" />
    </Type>
  </Table>
  <Table Name="dbo.RepeatScheduleEntry" Member="RepeatScheduleEntries">
    <Type Name="RepeatScheduleEntry">
      <Column Name="RepeatScheduleEntryId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RepeatScheduleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RepeatDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NotificationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SMSNotificationSent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SMSMessageId" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SMSDateSent" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SmsSentLogId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="RepeatSchedule_RepeatScheduleEntry" Member="RepeatSchedule" AccessModifier="Internal" ThisKey="RepeatScheduleId" OtherKey="RepeatScheduleId" Type="RepeatSchedule" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ServerAction" Member="ServerActions">
    <Type Name="ServerAction">
      <Column Name="ServerActionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Function]" Member="Function" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EntityChanged" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FieldChanged" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OriginalValue" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="NewValue" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_ServerAction" Member="User" AccessModifier="Internal" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.ServerError" Member="ServerErrors">
    <Type Name="ServerError">
      <Column Name="ServerErrorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ErrorMessage" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_ServerError" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.SmsCampaign" Member="SmsCampaigns">
    <Type Name="SmsCampaign">
      <Column Name="SmsCampaignId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MessageContents" Type="System.String" DbType="VarChar(160) NOT NULL" CanBeNull="false" />
      <Column Name="OrganizationSelectedCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OrganizationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="SmsCampaign_SmsSentLog" Member="SmsSentLogs" ThisKey="SmsCampaignId" OtherKey="SmsCampaignId" Type="SmsSentLog" />
      <Association Name="SmsCampaign_SmsSentQueueItem" Member="SmsSentQueueItems" ThisKey="SmsCampaignId" OtherKey="SmsCampaignId" Type="SmsSentQueueItem" />
    </Type>
  </Table>
  <Table Name="dbo.SmsDeliveryReportLog" Member="SmsDeliveryReportLogs">
    <Type Name="SmsDeliveryReportLog">
      <Column Name="SmsDeliveryReportLogId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CellPhoneNumber" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MessageId" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MessageContents" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DateReceivedOriginalFormat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Campaign" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DataField" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nonce" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NonceDateOriginalFormat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Checksum" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="SmsProviderCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SmsSentLogId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="SmsSentLog_SmsDeliveryReportLog" Member="SmsSentLog" AccessModifier="Internal" ThisKey="SmsSentLogId" OtherKey="SmsSentLogId" Type="SmsSentLog" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.SmsMessageTemplate" Member="SmsMessageTemplates">
    <Type Name="SmsMessageTemplate">
      <Column Name="SmsMessageTemplateId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrganizationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="VarChar(140) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Organization_SmsMessageTemplate" Member="Organization" AccessModifier="Internal" ThisKey="OrganizationId" OtherKey="OrganizationId" Type="Organization" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SmsProcessor" Member="SmsProcessors">
    <Type Name="SmsProcessor">
      <Column Name="SmsProcessorId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ExecutionInterval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastExecutionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="SmsProcessor_SmsProcessorLog" Member="SmsProcessorLogs" ThisKey="SmsProcessorId" OtherKey="SmsProcessorId" Type="SmsProcessorLog" />
    </Type>
  </Table>
  <Table Name="dbo.SmsProcessorLog" Member="SmsProcessorLogs">
    <Type Name="SmsProcessorLog">
      <Column Name="SmsProcessorLogId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SmsProcessorId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="LogMessageType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="SmsProcessor_SmsProcessorLog" Member="SmsProcessor" AccessModifier="Internal" ThisKey="SmsProcessorId" OtherKey="SmsProcessorId" Type="SmsProcessor" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SmsReceivedLog" Member="SmsReceivedLogs">
    <Type Name="SmsReceivedLog">
      <Column Name="SmsReceivedLogId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CellPhoneNumber" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MessageId" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MessageContents" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DateReceivedOriginalFormat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Campaign" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DataField" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nonce" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NonceDateOriginalFormat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Checksum" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="SmsProviderCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrganizationId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SubscriberId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SubscriberName" Type="System.String" DbType="VarChar(160)" CanBeNull="true" />
      <Column Name="MessageToOrganization" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DateReceived" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Organization_SmsReceivedLog" Member="Organization" AccessModifier="Internal" ThisKey="OrganizationId" OtherKey="OrganizationId" Type="Organization" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Subscriber_SmsReceivedLog" Member="Subscriber" AccessModifier="Internal" ThisKey="SubscriberId" OtherKey="SubscriberId" Type="Subscriber" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.SmsReceivedQueueItem" Member="SmsReceivedQueueItems">
    <Type Name="SmsReceivedQueueItem">
      <Column Name="SmsReceivedQueueItemId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CellPhoneNumber" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MessageId" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MessageContents" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DateReceivedOriginalFormat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Campaign" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DataField" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nonce" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NonceDateOriginalFormat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Checksum" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="SmsProviderCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SmsSentLog" Member="SmsSentLogs">
    <Type Name="SmsSentLog">
      <Column Name="SmsSentLogId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Success" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ErrorCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ErrorMessage" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CellPhoneNumber" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MessageId" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MessageContents" Type="System.String" DbType="VarChar(160)" CanBeNull="true" />
      <Column Name="TableReference" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RecordReference" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Tag" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SmsProviderCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SenderUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Delivered" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OrganizationId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SubscriberId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SubscriberName" Type="System.String" DbType="VarChar(160)" CanBeNull="true" />
      <Column Name="Campaign" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SmsCampaignId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="SmsSentLog_SmsDeliveryReportLog" Member="SmsDeliveryReportLogs" ThisKey="SmsSentLogId" OtherKey="SmsSentLogId" Type="SmsDeliveryReportLog" />
      <Association Name="Organization_SmsSentLog" Member="Organization" ThisKey="OrganizationId" OtherKey="OrganizationId" Type="Organization" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="SmsCampaign_SmsSentLog" Member="SmsCampaign" AccessModifier="Internal" ThisKey="SmsCampaignId" OtherKey="SmsCampaignId" Type="SmsCampaign" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Subscriber_SmsSentLog" Member="Subscriber" AccessModifier="Internal" ThisKey="SubscriberId" OtherKey="SubscriberId" Type="Subscriber" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.SmsSentQueueItem" Member="SmsSentQueueItems">
    <Type Name="SmsSentQueueItem">
      <Column Name="SmsSentQueueItemId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CellPhoneNumber" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="MessageContents" Type="System.String" DbType="VarChar(160) NOT NULL" CanBeNull="false" />
      <Column Name="TableReference" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RecordReference" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Tag" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SmsProviderCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SenderUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="OrganizationId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SubscriberId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SubscriberName" Type="System.String" DbType="VarChar(160)" CanBeNull="true" />
      <Column Name="Campaign" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SmsCampaignId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FailedToSend" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FailedToSendErrorMessage" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="SmsCampaign_SmsSentQueueItem" Member="SmsCampaign" AccessModifier="Internal" ThisKey="SmsCampaignId" OtherKey="SmsCampaignId" Type="SmsCampaign" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrganizationId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_WebRequestActivity" Member="WebRequestActivities" ThisKey="UserId" OtherKey="UserId" Type="WebRequestActivity" />
      <Association Name="User_Invoice" Member="Invoices" ThisKey="UserId" OtherKey="CreatedByUserId" Type="Invoice" />
      <Association Name="User_Order" Member="Orders" ThisKey="UserId" OtherKey="CreatedByUserId" Type="Order" />
      <Association Name="User_ServerAction" Member="ServerActions" ThisKey="UserId" OtherKey="UserId" Type="ServerAction" />
      <Association Name="User_ServerError" Member="ServerErrors" ThisKey="UserId" OtherKey="UserId" Type="ServerError" />
      <Association Name="Organization_User" Member="Organization" AccessModifier="Internal" ThisKey="OrganizationId" OtherKey="OrganizationId" Type="Organization" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.RepeatSchedule" Member="RepeatSchedules">
    <Type Name="RepeatSchedule">
      <Column Name="RepeatScheduleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SubscriptionId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="NotificationMessage" Type="System.String" DbType="VarChar(140) NOT NULL" CanBeNull="false" />
      <Column Name="ScheduleName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UnitOfMeasure" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DaysRepeatInterval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="RepeatSchedule_RepeatScheduleEntry" Member="RepeatScheduleEntries" ThisKey="RepeatScheduleId" OtherKey="RepeatScheduleId" Type="RepeatScheduleEntry" />
      <Association Name="Subscription_RepeatSchedule" Member="Subscription" AccessModifier="Internal" ThisKey="SubscriptionId" OtherKey="SubscriptionId" Type="Subscription" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subscriber" Member="Subscribers">
    <Type Name="Subscriber">
      <Column Name="SubscriberId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CellPhoneNumber" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(160)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Subscriber_SmsReceivedLog" Member="SmsReceivedLogs" ThisKey="SubscriberId" OtherKey="SubscriberId" Type="SmsReceivedLog" />
      <Association Name="Subscriber_SmsSentLog" Member="SmsSentLogs" ThisKey="SubscriberId" OtherKey="SubscriberId" Type="SmsSentLog" />
      <Association Name="Subscriber_Subscription" Member="Subscriptions" ThisKey="SubscriberId" OtherKey="SubscriberId" Type="Subscription" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="CountryId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CountryCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Country_PublicHoliday" Member="PublicHolidays" ThisKey="CountryId" OtherKey="CountryId" Type="PublicHoliday" />
    </Type>
  </Table>
  <Table Name="dbo.PublicHoliday" Member="PublicHolidays">
    <Type Name="PublicHoliday">
      <Column Name="PublicHolidayId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="EventName" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="DateIdentifier" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HolidayDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Country_PublicHoliday" Member="Country" AccessModifier="Internal" ThisKey="CountryId" OtherKey="CountryId" Type="Country" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subscription" Member="Subscriptions">
    <Type Name="Subscription">
      <Column Name="SubscriptionId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrganizationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="SubscriberId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CustomerFullName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CustomerEmailAddress" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CustomerIdentifier" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CustomerPhysicalAddress" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CustomerNotes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Subscription_RepeatSchedule" Member="RepeatSchedules" ThisKey="SubscriptionId" OtherKey="SubscriptionId" Type="RepeatSchedule" />
      <Association Name="Organization_Subscription" Member="Organization" AccessModifier="Internal" ThisKey="OrganizationId" OtherKey="OrganizationId" Type="Organization" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Subscriber_Subscription" Member="Subscriber" AccessModifier="Internal" ThisKey="SubscriberId" OtherKey="SubscriberId" Type="Subscriber" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>