//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Figlut.Repeat.ORM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PAULKOLOZSV38D1\\MSSQLSERVER2012;Initial Catalog=FiglutRepeat;Persist " +
            "Security Info=True;User ID=sa;Password=27830529")]
        public string FiglutRepeatConnectionString {
            get {
                return ((string)(this["FiglutRepeatConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PAULKOLOZSV38D1\\MSSQLSERVER2012;Initial Catalog=FiglutRepeat;Integrat" +
            "ed Security=True")]
        public string FiglutRepeatConnectionString1 {
            get {
                return ((string)(this["FiglutRepeatConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PAULKOLOZSV38D1\\MSSQLSERVER2012;Initial Catalog=FiglutRepeat;Persist " +
            "Security Info=True;User ID=sa")]
        public string FiglutRepeatConnectionString2 {
            get {
                return ((string)(this["FiglutRepeatConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PAULKOLOZSV38D1\\MSSQLSERVER2012;Initial Catalog=FiglutRepeat;Persist " +
            "Security Info=True;User ID=sa")]
        public string FiglutRepeatConnectionString3 {
            get {
                return ((string)(this["FiglutRepeatConnectionString3"]));
            }
        }
    }
}
